fos_rest:
  body_listener: true
  param_fetcher_listener: force
  format_listener:
    enabled: true
    rules:
       - { path: ^/api/, priorities: [ html, json, xml ], fallback_format: ~, prefer_extension: true }
       - { path: '^/', priorities: [ 'html', '*/*'], fallback_format: html, prefer_extension: true }

  view:
    view_response_listener: true
    formats:
      json: true
      xml: false
      rss: false
    mime_types:
      json: ['application/json', 'application/x-json']
  exception:
    enabled: true
